### ISSUE TITLE
CraftTweaker commands to print out various things

### ISSUE THREAD

**Issue by pupnewfster** [mekanica/mekanica#10]
Similar to how `/ct fluids` or `/ct entities` works. Should be very easy to add.

**Comment by pupnewfster** [comment]
`/ct gases` and `/ct infuseTypes` have been implemented as of https://github.com/mekanica/mekanica/commit/ce1e1b32bf165667bda216d0d0f65b6a9b033b44

**Comment by pupnewfster** [comment]
Makes commands to list all the different recipes from the machines.
Probably will use the format `/ct mekrecipe <machinetype>` or `/ct <machinetype>Recipe`

**Comment by pupnewfster** [comment]
`/ct mekrecipe <mainetype>` works with tab complete as of https://github.com/mekanica/mekanica/commit/6ad9a4d23ce2fbed702d55bf3a38e0f6b5275a61

**Comment by dizzyd** [comment]
Released in 1.0.0.
