### ISSUE TITLE
[1.1.0] Digital miner duping

### ISSUE THREAD

**Issue by Gamertech** [mekanica/mekanica#102]
#### Issue description:
I've got a digital miner set up clearing out an area. When it mines a block it puts it in its inventory as per normal. 1 block per 1 block mined.

The issue is, when outputting to an inventory (in this case a Multi-storage Enderlink chest on the back output port) the miner is pumping out stacks of blocks, but the inventory in the miner keeps climbing at 1:1. The stored blocks can be removed by hand as normal.

It seems to be outputting the mined blocks but not clearing the inventory afterwards.

When the internal inventory is full, the miner stops working (to mine meter stops and world blocks stop vanishing) but continues to pump out stacks. The output stacks seem to be matching the number of blocks in the inventory, so if there's 64 of something, it'll output that, if there's 30 of another block, it'll output 30.

This occurs both via auto-eject to the chest or using logistics conduits. Nothing related showing in debug.

#### Steps to reproduce:
1. Setup and run a Digital Miner
2. Output to an external storage
3. Observe that the miner is outputting blocks, but the inventory isn't being cleared

#### Version (make sure you are on the latest version before reporting):
**Forge:** 5.808
**Mekanica:** 1.1.0
**Mek Gen:** 1.1.0

**Comment by dizzyd** [comment]
@Gamertech - I'll take a look at this tomorrow (3/24). I've been using the DigitalMiner in my test worlds and haven't seen this, but will try to reproduce this specific setup. If you have a test world you can share, that would accelerate things. :)

**Comment by pupnewfster** [comment]
I managed to track this down and it turns out it is an issue with some other machines as well not working properly with automation, so I am working on fixing all the other locations.

**Comment by pupnewfster** [comment]
Fixed in 1.1.2

**Comment by Gamertech** [comment]
Can confirm. Fixed for me too. Cheers :)
