### ISSUE TITLE
Mekanism Fusion Reactor additional configs?

### ISSUE THREAD

**Issue by Testo0987** [mekanica/mekanica#103]
Hello everybody.
The other day i was messing around with the Mekanism reactor configs, and noticed that when i edited the power production, it increased the amount the reactor produced but it would never output above 400MRF. This is because of the storage buffer, of 400MRF. The reactor said it was generating more than 400MRF, but you could only output 400MRF no matter how many ports you had. Since the reactor doesn't have that may config options, it would be nice to have a config for the buffer energy.

Thanks!
P.S.
I'm new to GitHub, so sorry if i posted this in the wrong page, i don't know how to do otherwise.

**Comment by pupnewfster** [comment]
It appears the max output of a port is hardcoded to 1,000,000,000 (Joules). This is probably something that can be fixed when we internally change to FE. Though I will look into it to see if I can up it at all before then.

**Comment by Testo0987** [comment]
Thank you for the info and the quick reply!

**Comment by Testo0987** [comment]
Also, if you don't mind, could you tell me where the code is located within the mod? Like for ex. in one of the class files in mekanismgenerators.jar, if it is allowed?
Thanks.

**Comment by pupnewfster** [comment]
I mean it is open source so I don't know why it wouldn't be allowed. But it is right here https://github.com/mekanica/mekanica/blob/master/src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorPort.java#L271

**Comment by Testo0987** [comment]
Thank you so much! I've been looking for this for a while now!

**Comment by Testo0987** [comment]
Hello, i noticed that you updated the configs for all the new bugs/features and wondered if they are available for download. I new to GitHub so i'm not familiar with this.
Thanks.

**Comment by pupnewfster** [comment]
You could fork it manually and compile it yourself, however I recommend just waiting until dizzy gets a chance to verify the PRs tomorrow, as we are likely to release a version then to fix the dupe bug with Digital Miners.

**Comment by Testo0987** [comment]
Alright, thanks for the info!

**Comment by Testo0987** [comment]
Sorry for so many questions, but will the update containing the bug fixes and new features be only for Mekanica or for the Mekanism modules (Generators, tools) too?

**Comment by pupnewfster** [comment]
Mekanica and the submodules (generators and tools) all get updated at the same time.

**Comment by Testo0987** [comment]
Thanks!

**Comment by Testo0987** [comment]
Hello, i was wondering if you increased maximum transfer because i didn't see it in the newest version, and if you also added a config for that.
Thanks for the update!

**Comment by Testo0987** [comment]
Hello, i was wondering if you increased maximum transfer because i didn't see it in the newest version, and if you also added a config for that.
Thanks for the update!

**Comment by pupnewfster** [comment]
There is no config option for it as I changed it to the max value it can be. (This will still end up being increased once internally things switch to FE from Joules as of the ratio being 1:2.5) And we haven't released a new version yet with this. I recommend just waiting patiently or figuring out how to compile modes yourself and download the branch that has it. #108 which has the change, hasn't even been merged yet.

**Comment by Testo0987** [comment]
Thanks for the info!

**Comment by Testo0987** [comment]
Hi, i downloaded V1.12 of Mekanica and in the changelog said the comments were merged, but i can't seem to find the config for the reactor output. It can also only output 400MRF, like last time. I am wondering if i missed something.
Thanks.

**Comment by Testo0987** [comment]
Side note:
Ever since i downloaded Mekanica and replaced Mekanism, my FPS went up a decent amount. You guys did a great job on that.

**Comment by pupnewfster** [comment]
There is no config option for it. But that means that I was right on the theory it can only eject as much as it stores. So you will have to wait a while no idea when it will be able to go higher than 400 MRF. It isn't really a high priority.

**Comment by Testo0987** [comment]
Ok, got it!

**Comment by dizzyd** [comment]
It sounds like we got this issue resolved (mostly). I'm going to close this issue; @Testo0987 if you run into other problems, please feel free to reopen.
