### ISSUE TITLE
Logistical Sorter GUI Overlap w/ Inventory

### ISSUE THREAD

**Issue by LukewarmYeti** [mekanica/mekanica#11]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

https://imgur.com/a/CdoH3Fi

Opening the Logistical Sorter GUI seems to also open the inventory, therefore both of them overlapping, making it hard to click on anything. I'm currently running at 2560x1440, not sure if that even matters.

#### Steps to reproduce:
1. Place logistical Sorter
2. Open GUI
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2815
**Mekanism:**  Mekanica-1.12.2-1.0.0.b1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Released in 1.0.0.
