### ISSUE TITLE
Rotary condensentrator requiring fluid input and outputting gas on the same side

### ISSUE THREAD

**Issue by saulrh** [mekanica/mekanica#110]
#### Issue description:

As titled - instead of requiring fluids from one side and outputting gases on the opposite side, the rotary condensentrator requires fluids to be inserted on the same side that it outputs gases.

I was able to work around it with an entangloporter; phantomfaces would also work.

#### Steps to reproduce:
1. Place Rotary condensentrator. Set to deconsdensentrating. Place water source so that the condensentrator's fluid buffer fills and it starts producing water vapor.
2. Place gas tank next to condensentrator on side opposite water source. Make sure sides are configured to accept. Observe gas tank not filling with gas.
3. Break water source. Break gas tank and place where water source was. Ensure gas tank sides are configured to accept. Observe gas tank filling with gas.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2781
**Mekanica:** 1.12.2-1.1.1
**Other relevant version:** 

### Screenshot:

https://i.imgur.com/3pS1i8v.png

**Comment by saulrh** [comment]
Note: This is a slightly-modified Enigmatica 2 Expert 1.54 server - I manually changed from Mekanism 1.12.2-9.4.13.349 to Mekanica earlier today and found this while figuring out why my fusion reactor had gone down.

**Comment by pupnewfster** [comment]
Turns out I grabbed the wrong sides for a few things so fixed it to use the proper sides. Sorry about that and thanks for the report. https://github.com/mekanica/mekanica/commit/b55fb42453a818db0c2d5f03ff67cb86c61368e5

**Comment by pupnewfster** [comment]
Fixed in 1.1.2
