### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by mattrix444** [mekanica/mekanica#111]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
crash on startup

#### Steps to reproduce:
1.press play
2.gets to the end of 2/7 and crashes
3. press F to pay respects

#### Version (make sure you are on the latest version before reporting):
**Forge:*2823* 
**Mekanica:*1.12.2-1.1.1* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest.log](https://github.com/mekanica/mekanica/files/3000506/latest.log)

[gist/pastebin/etc link here]
https://paste.dimdev.org/iwireqerig.mccrash

**Comment by dizzyd** [comment]
As discussed in the Discord, this appears to be a multi-way conflict which we can't resolve directly in Mekanica. If you get new information, please feel free to re-open this ticket.
