### ISSUE TITLE
Gasses and liquids are both fluids

### ISSUE THREAD

**Issue by Poppycocks** [mekanica/mekanica#114]
There is little to no distinction between gasses and liquids, and at this point when other mods implemented gasses as fluids, it's weird to have gasses separate. 

Pros:
1. Consistency with other mods
2. One less pipe type to worry about
3. Can fix weird outputs such as:
 a. Sulphur Trioxyde + water wapor = gasseous sulphuric acid
 b. gaseous ore SLURRIES
4. Can put gas into dynamic tanks without additional work
5. Fluid piping, filtering and storage solutions from other mods
6. More freedom with machine input/output in general

Cons:
1. Rotary Condensentrator will see less use

**Comment by aidancbrady** [comment]
Rather than trash the gas system, we're likely going to do some reworking of functionality and content in v10 to really differentiate it from the fluid system.
