### ISSUE TITLE
Digital Miner Ticking

### ISSUE THREAD

**Issue by Yamza** [mekanica/mekanica#117]
#### Steps to reproduce:
1. Place a Digital Miner
2. Configure filter (unsure that this is needed)
3. Scan with Laggoggles

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2815
**Mekanica:** mekanica-1.12.2-1.1.2
**Other relevant version:** ATM3: Remix 1.2.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

This happens to be the one I found today, but I can add more examples as I find them.
https://i.imgur.com/Ckd8Qz7.png
https://i.imgur.com/LjSJUQn.png
https://i.imgur.com/3ebdadX.png

**Comment by dizzyd** [comment]
I investigated this briefly; the DigitalMiner is recalculating the chunk set it should run over...every tick. According to the profiler, this accounts for 70% or so of the lag you're seeing; I'll look at getting this fixed for the next release.

**Comment by dizzyd** [comment]
Fixed in PR #134.
