### ISSUE TITLE
induction matrix cell and provider don't render colours in inventory

### ISSUE THREAD

**Issue by temp1011** [mekanica/mekanica#121]
git tree checked out at 5dd3cf3bbdde60bcd6c25f1bf4e1837067272993.

![picture](https://user-images.githubusercontent.com/34900092/55032370-a2a20b80-5008-11e9-8015-0ebcf1b3baa1.png)

the blocks are the correct colour in world.

**Comment by dizzyd** [comment]
I'm assigning this one to you @temp1011 :)

**Comment by temp1011** [comment]
Just the mekanica + forge + ctm works fine, so this is likely a cross mod bug or something that only happens in development

**Comment by temp1011** [comment]
after running `./gradlew clean setupDecompWorkspace idea genIntellijRuns` this no longer happens. I have no idea what caused this but it seems it was an issue with my development environment only.
