### ISSUE TITLE
"Multiblock Formed" text reappearing after leaving general area

### ISSUE THREAD

**Issue by Testo0987** [mekanica/mekanica#122]
#### Issue description:
I built a fusion reactor and an induction matrix in my world, and when i finished it said "Multiblock Formed", but when i left the general area and came back, the text popped up again.

#### Steps to reproduce:
1. Open up a world and make a multiblock (in this case i have a fusion reactor and an induction matrix in the same area)
2. Leave the general area (maybe 100 blocks, probably less)
3. Observe the "Multiblock Formed" text in blue.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2 V2808** 
**Mekanica: 1.1.2 (Latest)** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
When you left the nearby area the chunks unloaded. It reloading made the multiblock form again. If you chunkload the area you should not see the message appear.
