### ISSUE TITLE
Energy Network Update 6% CPU Usage

### ISSUE THREAD

**Issue by Yamza** [mekanica/mekanica#123]
#### Issue description:
https://i.imgur.com/sjUdw4V.png

#### Steps to reproduce:
This is reported from a server with a bit of Mek usage
https://sparkprofiler.github.io/#7ryov0J6EG

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2815
**Mekanica:** 1.1.2
**Other relevant version:** ATM3: Remix 1.2.0

This is all the Mek in use on the server
https://imgur.com/a/U6IdMQu

**Comment by dizzyd** [comment]
Thanks for this - it's super helpful. I've got a lead and think I can probably cut that in half in the next release.

**Comment by dizzyd** [comment]
This won't land in 1.2.0, unfortunately. I ran out of time. Once we get Mekanica/Mekanism merged together, I'll look at this again (probably a week or so).

**Comment by aidancbrady** [comment]
Merging this with #105.
