### ISSUE TITLE
Crash at the world Loading with the alpha 1.2.0a1

### ISSUE THREAD

**Issue by Fireztonez** [mekanica/mekanica#125]
I have installed the new Alpha version question of test the improuvements and try to look if there have somes issue with the new item transport improvements and for somes reason I get a crash directly when I try to load the world, so with my modpack it just doesn't work at all...

No worry, I know, this is an Alpha Version and I expect somes bugs or crash, but, for sure, I have to provide you the crash logs, so here it is!!
https://gist.github.com/Fireztonez/423d08138deb1bc39ef7a51146aa260a

On the crash report I didn't see anything really about Mekanica, but, I just test again with the previous version and the world load Ok, so for sure, this is caused by something on Mekanica

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.235.2823
**Mekanica:** 1.2.0a1

**Comment by dizzyd** [comment]
Are you running a custom modpack, by chance? This crash is happening in a mod that makes no sense, so I'll probably have to try and re-create it.

**Comment by Fireztonez** [comment]
Yes I running that in a custom modpack made for my community, but I will made it public when the beta testing will be finished.  But if you need, I can provide you the modpack question of testing directly yourself.

**Comment by dizzyd** [comment]
Closing after discussion on Discord. Failure seemed to be intermittent and not directly related to Mekanica. @Fireztonez - please reopen if you discover something new. :)
