### ISSUE TITLE
[1.0.0b1] Hotbar displayed over UI bug

### ISSUE THREAD

**Issue by Gamertech** [mekanica/mekanica#13]
#### Issue description:
Mekanica machine UI's are displaying the inventory hotbar over the top

#### Steps to reproduce:
1. Open a machine's UI (easier to see when opening the sides config, or the fusion reactors stats page)
2. Enjoy all the hotbarness

#### Version (make sure you are on the latest version before reporting):
**Forge:** 5.2808
**Mekanica:** 1.0.0b1
**MekanicaGen:** 1.0.0b1

https://i.imgur.com/IyqlK19.jpg

**Comment by Gamertech** [comment]
Oh whoops, duplicate sorry, missed the previous issue with the logistical sorter.

Just point out this affects all machines, not just the sorter.

**Comment by pupnewfster** [comment]
I tested and I can confirm that the fix for the other issue also fixes this.
