### ISSUE TITLE
Major Performance Issue Between Jumping Two Versions 

### ISSUE THREAD

**Issue by FriendlyGamer** [mekanica/mekanica#130]
On the behalf of Chimera I am pushing this on here for my recent discovery of upgrading the mod.  
![2019-03-27_16 53 12](https://user-images.githubusercontent.com/38051855/55116574-1baf6a80-50be-11e9-895f-96ee5ec4c6a5.png)

**Comment by SadChimera** [comment]
Thanks! I'll play around with this over the next couple days. Meanwhile Diz will continue overhauling logistical transporters.

**Comment by dizzyd** [comment]
Fixed by #124. Will be part of 1.2.0 release.
