### ISSUE TITLE
Investigate disabling EnableAmbientLighting by default

### ISSUE THREAD

**Issue by dizzyd** [mekanica/mekanica#14]
Per: https://www.reddit.com/r/feedthebeast/comments/b0clk3/mekanica_tools_and_machines_a_fork_of_mekanism/eiet4up

**Comment by Ligands** [comment]
Relevant potential alternative idea I thought of when replying to a comment on that thread:

> Perhaps machine lights should just do what Thermal Expansion does- don't immediately shut off when the machine stops running, but wait for a few seconds first, so that you don't get the 'flickering' problem.

**Comment by ate0ate** [comment]
There's some good points made here by King Lemming regarding this issue in TE. CoFH/Feedback#916

I just wanted to add my opinion here so please do not take what I'm saying as any kind of counter-point or anything. I personally love the lights. Immersion is crucial to my personal enjoyment when playing MC or gaming in general. Using modded machines that do not offer feedback of some sort really make things feel repetitive or sort of pointless. Kind of like a magic block you just throw something into a GUI and get a different item back. I know it seems silly, but the little things do make a difference, at least for me.

Aside from that, I think the buffer idea is a smart move I do want to point to what King Lemming said about improving your build being a better solution to this type of issue. There should be a steady work flow so there is always enough resources for the processing machine to pull from. If you have a large amount of machines shutting on and off as they chew through supplies, take one away or increase the supply to match the demand. Following that logic alone should eliminate much of this. 

The only other thing I can think of that can be optimized to decrease flickering a bit would be timings of machines being made to match others. Take a grinder and furnace for example. The grinder should work at at least the same pace as the furnace as to keep a steady flow going. This is just an example to explain what I mean and can be applied to any system. That is really simplifying things, especially in Mek, and I can only imagine that it is much easier said than implemented lol. Just some thoughts.

**Comment by jburrows82** [comment]
As discussed on the reddit post linked, I also would prefer to have ambient lighting on by default. However, I suggest changing the behavior of tying the ambient lighting not to the status of the machinery processing, but rather if it has energy. Once the internal energy buffer hits 0, wait 100 ticks to receive any energy, then if not, turn off the ambient lighting from the machine. 

I feel the sound and/or texture/animation indicator from machinery "working" is a more practical indicator than lighting the area itself. If a machine has energy, it's basically on and ready right? Then when it has no power, it's off. My coffee maker doesn't have a status led only ambient lighting my kitchen when it's brewing, it's on all night long if it's plugged in and receiving power.

**Comment by dizzyd** [comment]
Released in 1.0.0.
