### ISSUE TITLE
"NullPointerException: Rendering ingredient" in JEI

### ISSUE THREAD

**Issue by DeadSix27** [mekanica/mekanica#144]
#### Issue description:
Crash in JEI (see reproduction steps)

#### Steps to reproduce:
1. Search for "capacitor bank" in JEI
2. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** Forge 14.23.5.2814
**Mekanica:** mekanica-1.12.2-1.2.0b2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/DeadSix27/c943df7fb9b684423c3ed49916691aa7

**Comment by temp1011** [comment]
Does it happen without optifine? And searching for an EnderIO item cases a mekanism crash??

**Comment by DeadSix27** [comment]
Ugh, I must have submitted that in a rush when tired, somehow associated typing "capac.." with it being an EIO issue, despite nothing in the stack trace hinting that.. ill report it to mekanism.  Sorry.
