### ISSUE TITLE
Sound muffler upgrades not working

### ISSUE THREAD

**Issue by Dannerick** [mekanica/mekanica#22]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In the latest beta versions, MekanismDz-1.12.2-9.5.0b3, from the Enigmatica 2 mod pack, the sound muffler upgrades applied to machines don't appear to be working. In the previous release version, MekanismDz-1.12.2-9.4.17, they were working correctly. 

Also, the noise from the jetpack is overly loud; in previous versions the sound was a soft background whoosh, now it is overwhelming. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2784
**Mekanism:** MekanismDz-1.12.2-9.5.0b3
**Other relevant version:** Enigmatica 2 mod pack

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hi @Dannerick - could you please try the 1.0.0b1? There was a bug in the muffling calculations that was corrected there. :) Thanks!

**Comment by dizzyd** [comment]
Closing this issue; happy to re-open if it's still a problem with 1.0.0b1 or later. :)
