### ISSUE TITLE
Steel Chestplate and Tools missing Ore Dict for Iron Ingots

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#25]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Iron Ingots used in the Steel Armor recipes don't use Oredict
Iron Ingots used in the Steel Tools Recipes don't use Oredict aswell

#### Steps to reproduce:
1. Search Mekanica Tools
2. Click on Steel armor Recipes and see Steel is Ore Dict but not Iron 
3. Click on Steel Tool Recipes and see that Iron is not Oredict

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.5.2815
**Mekanism:** mekanica-tools-1.12.2-1.0.0b1.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Released in 1.0.0.
