### ISSUE TITLE
Paxel Recipes

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#26]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Paxel Recipes don't have sticks using <ore:stickWood> to use different types of sticks to make Paxel recipes. These being oreDict would help with people who like using Forestry or Natura sticks in there packs.

#### Steps to reproduce:
1. Search Mekanica Tools
2. Click on any Paxel Recipes and see Sticks are not Oredict
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.5.2815
**Mekanism:** mekanica-tools-1.12.2-1.0.0b1.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Released in 1.0.0.
