### ISSUE TITLE
[Suggestion] Make Ore Gen disabling easier

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#39]
Hi, I was Wondering is there a way you guys could add a option in the config to disable all Ore gen cause as it sits, the only way to disable Ore gen is going next to let's say Salt and putting a 0 to stop it. I was hoping we could get a better way to do this then having to use numbers to disable gen

Thanks Again for reading this.

**Comment by dizzyd** [comment]
Gonna mark this as a possible enhancement for the release a few weeks out. Thanks!

**Comment by bookerthegeek** [comment]
Jsut a general config cleanup thread maybe?

Voice server is still in the config and under controls in game.
