### ISSUE TITLE
Fusion Reactors Shutting Down Due to Unexpected Heat Loss 

### ISSUE THREAD

**Issue by FriendlyGamer** [mekanica/mekanica#51]
#### Issue description:
These reactors (fusion) will start up and instantly or at least ticks later lose heat despite having a constant supply of T and D on both lines at the rate specified in the GUI (air cooling requires at least 2mb/t for each so we set the reactor to inject that much per tick)  

#### Steps to reproduce:
1. Build the reactor
2. Start the reactor up normally
3. Observe the heat loss despite proper fuel levels 

#### Version (make sure you are on the latest version before reporting):
**Forge: ending 2815 for Minecraft 1.12.2
**Mekanism:9.4.18 (I know it's not the latest but it just came out a few hours ago and we can't just update that quickly, if it confirmed to be fixed in the latest out just let me know).  
**Other relevant version:Minecraft 1.12.2

#### If a (crash)log is relevant for this issue, link it here: NA it's a in game mechanic issue

Please let us know if this is end user error of running them and if so what else we should be doing beside keeping the fuel levels in check. Otherwise let us know if it just the matter of updating to the latest that just came out a few hours ago or when the fix will be pushed if it indeed a mechanic issue. 

Thanks in advance!

**Comment by dizzyd** [comment]
Hi @FriendlyGamer - I have not seen this and do not know of any issues along these lines. If you would, please construct a fusion reactor in a creative world with creative tanks of D&T feeding it and see if this still happens? I'm happy to look into it if you can reproduce this way. :)

**Comment by FriendlyGamer** [comment]
> Hi @FriendlyGamer - I have not seen this and do not know of any issues along these lines. If you would, please construct a fusion reactor in a creative world with creative tanks of D&T feeding it and see if this still happens? I'm happy to look into it if you can reproduce this way. :)

Sorry for the mix up but I gotten the final conclusions here... 
Apparently DT is NOT rate limited like the D and T gases are. So when we rate limited the amount by the separator (producing 4DT/tick) we were able to bring the reactor to above the sustainable temperature to keep the reactions going. I am assuming if it at 2DT/tick it will still works.  

But why in the world does it eat DT, D and T and why does it eat DT at whatever the PUMPED in rate over the rate limited injected rate? 

Thanks in advance!

**Comment by Gamertech** [comment]
If you're pumping in D&T separately, then just setting the reactor to 2 fuel rate and igniting should be self-maintaining. From a cold start, I see a burst of heat then it slowly increases over time to the temps shown in the stats tab and stays there.

iirc DT burns at a much faster rate, in a burst useful for igniting the reactor but not efficient enough to actually fuel it long-term. It has much higher consumption rate than the intended D&T fuel mix.

**Comment by FriendlyGamer** [comment]
> If you're pumping in D&T separately, then just setting the reactor to 2 fuel rate and igniting should be self-maintaining. From a cold start, I see a burst of heat then it slowly increases over time to the temps shown in the stats tab and stays there.
> 
> iirc DT burns at a much faster rate, in a burst useful for igniting the reactor but not efficient enough to actually fuel it long-term. It has much higher consumption rate than the intended D&T fuel mix.

Are you saying that DT Fuel is worst or the separate mixing of them inside the reactor itself? Because the last bit is confusing me which is which your talking about.  

Thanks in advance!

**Comment by FriendlyGamer** [comment]
@dizzyd I had further tested this to see what was going on exactly so I found out...  

You CAN feed it the other fuels only but it's has to be injected at double the rates (4) in order to maintain the reactor above it's min (above 100MK). BUT it will NOT work as intended at 2 as because it will drop below the 100MK for minutes on end to about 99.03MK and kept on dropping. 

I don't know if the reactions would keep on going but I can't sit there for hours just to find out. BUT as I said on the server it WILL lead to a non running reactor in the end.   

Because of this I do believe something is indeed wrong to some extent.
![2019-03-16_23 19 29](https://user-images.githubusercontent.com/38051855/54484765-a97b9200-4842-11e9-892f-09f5514b36a6.png)
![2019-03-16_23 19 12](https://user-images.githubusercontent.com/38051855/54484766-a97b9200-4842-11e9-9381-7e6df49890c1.png)

**Comment by Gamertech** [comment]
Sorry, the mixed DT fuel input on its own burns hot instantly which makes it great for igniting the reactor, but uses much more of it to maintain the reactor as it burns out too fast.

Inputting deuterium and tritium separately is the best for ongoing fueling of the reactor.

**Comment by FriendlyGamer** [comment]
> Sorry, the mixed DT fuel input on its own burns hot instantly which makes it great for igniting the reactor, but uses much more of it to maintain the reactor as it burns out too fast.
> 
> Inputting deuterium and tritium separately is the best for ongoing fueling of the reactor.

Thanks! Then I am confused on why the above is happening at the inject rate of 2 for the air cooled reactors we have and in my recent testing.

**Comment by dizzyd** [comment]
We spent some time trying to recreate this situation on Discord but were unable to see it. As discussed, please reopen this ticket if you get any new information. :)
