### ISSUE TITLE
[Suggestion/Question] Universal Cables support for IC2/Tech Reborn

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#55]
Hi, 
I noticed that some people love to still use IC2/Tech Reborn and was wondering if there is any Cable support for these mods so that Universal Cables works on there machines

**Comment by ReiDaTecnologia** [comment]
Mek cables convert any energy to any energy man
I use it for IC2/Tech Reborn machines

**Comment by SacrificialFlame** [comment]
I was posting this cause of any issues posted on Mekanism Github about Universal Cables not Connecting with IC2 Machines. @ReiDaTecnologia

**Comment by pupnewfster** [comment]
Could you at the very least maybe link some of them? I haven't had any issues in the past using power cables with either IC2 or Tech Reborn. (Other than at one point for getting powers out of IC2 generators I had to manually set the cable to extract). It is a bit hard to track bugs down/try to fix things if we don't even know what is wrong.

**Comment by SacrificialFlame** [comment]
https://github.com/aidancbrady/Mekanism/issues/5280

**Comment by dizzyd** [comment]
@SacrificialFlame - I've tried to reproduce the linked issue a couple of different ways, including installing the exact version of Enigmatica 2 in the original report, variations of IC2/Mekanism/Mekanica/etc. In no case can I get it to reproduce. :/

If you can provide a test case/world where this is happening, I'd be happy to investigate further. For the moment, we'll close this until we have something more concrete. :)
