### ISSUE TITLE
CoFHCore crash during initialization

### ISSUE THREAD

**Issue by WarMind666** [mekanica/mekanica#57]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  2185
**Mekanism:**  Mekanica-1.12.2-1.0.0
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/yqy7J09U
[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hey @WarMind666 - do you have a manifest.json that you can share? I tried to reproduce this with just CoFH* and Mekanica and couldn't get it to crash. Reading through the log, I see a NPE near the end of the first stack trace and I suspect there's something else going on there...maybe a circular dependency that's causing problems.

**Comment by WarMind666** [comment]
Put in the manifest.json from exporting the modpack through the Twitch launcher.

https://pastebin.com/HA7vG7dN
