### ISSUE TITLE
Machine sound still run when is turn off on the setting

### ISSUE THREAD

**Issue by Fireztonez** [mekanica/mekanica#77]
Hello,
I have change recently on my modpack from Mekanism to Mekanica, and I have change the machine sound setting to false, quetsion to disabled, but, now, the sound still play... I just look back on the config and the setting is still OFF, so, I think this is a bug...

I can't confirm if this is the case for all machines, but I have try different machines like enrichment chamber, Purifying Chamber, Purifying Factory, Enrichment Chamber and Factory and the Crusher, and all that machine still have the sound...

![machine-sound-mekanica](https://user-images.githubusercontent.com/19277301/54640562-7ca7c480-4a66-11e9-8365-882b7c425493.png)

and I confirm in the mekanism.cfg, the option is still disabled:
`B:EnableMachineSounds=false`

#### Steps to reproduce:
1.Turn Off Machine Sound
2. Place and try a machine
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2815
**Mekanica:  1.0.0
**Mekanica Tools:  1.0.0
**Mekanica Generator:  1.0.0

**Comment by pupnewfster** [comment]
I am pretty sure this is fixed by https://github.com/mekanica/mekanica/commit/39424224a2e3a87dec50db7b4658a52e5f04b155

**Comment by dizzyd** [comment]
Hi @Fireztonez - this is a known bug that is now fixed in development. See https://github.com/mekanica/mekanica/commit/39424224a2e3a87dec50db7b4658a52e5f04b155. We'll be shipping a new release at the end of this week with the bug fixed. Thanks!

**Comment by Fireztonez** [comment]
Perfect, thank's!
