### ISSUE TITLE
Power Input doesn't work after upgrading normal machine to basic tier factory (At least With EnderIO and XNet cable)

### ISSUE THREAD

**Issue by Fireztonez** [mekanica/mekanica#78]
When you upgrade a normal machine to the Basic Factory Tier in world, the machine doesn't accept power anymore, unless you break-it and place-it back in the world... After you place it back, the machine will work normally without any issue! I remember aving the same issue with mekanism before, so the problem is not new...

I know this issue appen with Enrichment Chamber, Metallurgic Infuser and the Crusher... I'm not sure for other machines, I don't try yet.

This issue appen for what I see with EnderIO Conduit and XNet Cable, but work great with Mekanism Universal Cable and Thermal Machine for what I see... I do not have try all other mods, like Extra Utils, because is not in my pack ;)

#### Steps to reproduce:
1. Place a normal Machine, like Enrichment Chamber or Crusher 
2. Upgarde it with the Basic Tier Installer
3. Use-it... The power already there is still there, but, when you use, it will ta empty the buffer doesn't input more power
4. Break it with a pickaxe or with a wrench and place it back 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2815
**Mekanica:** 1.0.0  (You should possibly edit your template and replace Mekanism by Mekanica ;-) )
**Other relevant version:** Same with Mekanism 9.6.0.351

**Comment by pupnewfster** [comment]
Fixed in Ender IO as of https://github.com/SleepyTrousers/EnderIO/commit/f159a527e5da27a15864442be73164601471a566 the next version of Ender IO will have this working.

For XNet is it just energy or is it all connection types? (I will make an issue on their tracker once I find out.)

**Comment by Fireztonez** [comment]
Sorry, I just try again to see and with XNET it doesn't seem to have an issue with that Right Now, the connection for Item and Power look good finally with XNET, after the upgrade.

So, if the problem is fixed in dev with EnderIO, I think the issue can be close now!
