### ISSUE TITLE
[Suggestion] Wind Generator Dimension Blacklist

### ISSUE THREAD

**Issue by DoctorMacc** [mekanica/mekanica#9]
Good day! As of right now, anyone can plop a wind generator in any dimension and it will work. This is most ridiculous in a scenario like Galacticraft, where you can place a wind generator on the Asteroid dimension and get power. Any chance we can get a blacklist for worlds where the wind generator will not work?

Thanks for the consideration, and good luck on the fork.

**Comment by pupnewfster** [comment]
Should be relatively easy to add. I think we only will need to add a check [here](https://github.com/mekanica/mekanica/blob/master/src/main/java/mekanism/generators/common/tile/TileEntityWindGenerator.java#L74), so something like `if (!inBlacklist && canSeeSky)`

**Comment by dizzyd** [comment]
Released in 1.0.0.
