### ISSUE TITLE
Atomic Disassembler Excavation Mode

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#97]
**Describe the the feature you'd like**
A clear and concise description of what you want.
Hi Again, I would like to suggest away to add a Excavation Mode with a blacklist to Atomic Disassembler.

This Excavation Mode would allow the Atomic Disassembler to mine whole veins of ore, cut down whole trees or any other tool based on how the Ore Excavation mod does. The Addition of a blacklist would also be helpful so said pack dev and players can choose what the Atomic Disassembler can Excavate during use.  This would be an amazing feature for people who want another option for Ore Excavation without having to add Ore Excavation.

**Describe alternatives you've considered**
n/a
**Additional context**
https://minecraft.curseforge.com/projects/ore-excavation

**Comment by vini2003** [comment]
This feature is already present as "Vein mode" or something isn't it?
It's not as powerful as OreExcavation but feels more balanced to me, at least.
