### ISSUE TITLE
Location of Digital Miner

### ISSUE THREAD

**Issue by dierke9** [mekanica/mekanica#98]
For a project im currently working on i need the location of the digital miner when it tries to mine a block (Using the BlockEvent.BreakEvent when the miner checks if it can mine the block) but currently the fakePlayer Entity gives the location of the block it will mine as location. Is there another way to find the location or can the location be changed to that of the miner and not of the block

**Comment by pupnewfster** [comment]
I agree this is silly, so I will fix the FakePlayer location later today. Before I commit the changes though I am going to loo through to see if any other FakePlayer instances are illogical like that.

**Comment by bookerthegeek** [comment]
Just a thought...

I believe it returned the location of the broken block to respect protect plugins so people could not digitally mine out another persons claim?

Will the new system allow the block break event to be cancelled if it is not returning the location of the block being broken?

**Comment by dierke9** [comment]
It will alsways be possible to find that position as it gets givin by the IBlockState parameter in that event. There are also other mods that do off stuff with the fakeplayer where they give worldspawn as their location. And RFTools builder gives the position of the builder itself aswell so everytjing should be fine.

You also should never listen to the location of the entity that mines a certain block to see if it can mine that block
